module.exports = {
    //  WAREHOUSE
    GET_MATERIALS: "GET_MATERIALS",
    ADD_MATERIALS: "ADD_MATERIALS",
    EDIT_MATERIAL: "EDIT_MATERIAL",

    GET_GOODS: "GET_GOODS",
    ADD_GOODS: "ADD_GOODS",
    EDIT_GOODS: "EDIT_GOODS",
    PAY_FOR_GOODS: "PAY_FOR_GOODS",

    //   PAYMENT
    GET_PAYMENTS: "GET_PAYMENTS",
    ADD_PAYMENTS: "ADD_PAYMENTS",
    EDIT_PAYMENT: "EDIT_PAYMENT",
    DELETE_PAYMENT: "DELETE_PAYMENT",

    //   FIN_ACCOUNT
    GET_ACCOUNTS: "GET_ACCOUNTS",
    ADD_ACCOUNT: "ADD_ACCOUNT",
    EDIT_ACCOUNT: "EDIT_ACCOUNT",

    //   ORDERS
    GET_ORDERS: "GET_ORDERS",
    ADD_ORDER: "ADD_ORDER",
    EDIT_ORDER: "EDIT_ORDER",

    ADD_ORDER_DETAIL: "ADD_ORDER_DETAIL",
    EDIT_ORDER_DETAIL: "EDIT_ORDER_DETAIL",
    ADD_PAYMENT_TO_ORDER: "ADD_PAYMENT_TO_ORDER",
    PAY_SALARY_FOR_ORDER: "PAY_SALARY_FOR_ORDER",

    //   STAFF_LIST
    GET_STAFF_LIST: "GET_STAFF_LIST",
    ADD_STAFF: "ADD_STAFF",
    EDIT_STAFF: "EDIT_STAFF",
    PAY_SALARY: "PAY_SALARY",
    GET_STAFF_SALARY: "GET_STAFF_SALARY",

    GET_FILE_BY_ID: "GET_FILE_BY_ID",
};
